package:
  name: mongomock
  version: 1.1.0

source:
  fn: mongomock-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mongomock/mongomock-1.1.0.tar.gz
  md5: edce0575757853316a4c4c8161cef2d5

requirements:
  build:
    - python
    - distribute
    - sentinels
    - six

  run:
    - python
    - sentinels
    - six

test:
  imports:
    - mongomock

about:
  home: https://pypi.python.org/pypi/mongomock
  license: BSD
