# This is a sample conda recipe, which is used for testing features
# in the conda build command.

package:
  name: pycosat
  version: 0.6.0

source:
  git_url: git@github.com:ContinuumIO/pycosat.git
  git_tag: 0.6.0
  patches:
    - foo.patch

requirements:
  build:
    - python
  run:
    - python

test:
  files:
    - uf20-098.cnf
  imports:
    - pycosat

about:
  home: https://github.com/ilanschnell/pycosat
  license: MIT
