package:
  name: drmaa
  version: 0.6

source:
  fn: drmaa-0.6.tar.gz
  url: https://pypi.python.org/packages/source/d/drmaa/drmaa-0.6.tar.gz
  md5: 40a04e2290aff947a08aeb97a55d1401
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - drmaa = drmaa:main
    #
    # Would create an entry point called drmaa that calls drmaa.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - drmaa

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://drmaa-python.googlecode.com
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
