package:
  name: r
  version: 3.0.2

source:
  fn: R-3.0.2.tar.gz
  url: http://rweb.quant.ku.edu/cran/src/base/R-3/R-3.0.2.tar.gz

requirements:
  build:
    - tk
  run:
    - tk

test:
  commands:
    - R -h
    - R --version
    - Rscript --version

about:
  home: http://www.r-project.org/
  license: GPL
